Pin urllib version in dev requirements file
When building sphinx docs in the CI environment we get this error:
    ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl'
    module is compiled with OpenSSL 1.0.2n  7 Dec 2017.
    See: https://github.com/urllib3/urllib3/issues/2168

This commit pins urllib to < 2.0.0 so we can avoid this error until the
environment the docs are built on supports uses a newer openssl version.